import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from './components/Navbar';
import { ToasterProvider } from './components/ToasterProvider';
import { UploadThingProviderClient } from './components/UploadThingProviderClient';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<UploadThingProviderClient />
				<Navbar />
				{children}
				<ToasterProvider />
			</body>
		</html>
	);
}
